"""initial migration

Revision ID: 39ecddf454ad
Revises: 
Create Date: 2026-07-23 20:07:06.227545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ecddf454ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructores_correo'), ['correo'], unique=True)

    op.create_table('fichas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre_programa', sa.String(length=200), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fichas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fichas_codigo'), ['codigo'], unique=False)

    op.create_table('aprendices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('tipo_documento', sa.String(length=5), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento', 'ficha_id', name='uq_aprendiz_documento_ficha')
    )
    with op.batch_alter_table('aprendices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aprendices_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_aprendices_ficha_id'), ['ficha_id'], unique=False)

    op.create_table('configuracion_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('umbral_amarillo', sa.Integer(), nullable=True),
    sa.Column('umbral_rojo', sa.Integer(), nullable=True),
    sa.Column('max_fallas_trimestre_laboral', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ficha_id')
    )
    op.create_table('sesiones_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ficha_id', 'fecha', name='uq_sesion_ficha_fecha')
    )
    with op.batch_alter_table('sesiones_asistencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_asistencia_ficha_id'), ['ficha_id'], unique=False)

    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('enlace_externo', sa.String(length=500), nullable=True),
    sa.Column('material_apoyo_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('requiere_archivo', sa.Boolean(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tareas_ficha_id'), ['ficha_id'], unique=False)

    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('aprendiz_id', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('enlace_repositorio', sa.String(length=500), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('calificada', sa.Boolean(), nullable=True),
    sa.Column('calificacion', sa.String(length=10), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('revisada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprendiz_id'], ['aprendices.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entregas_tarea_id'), ['tarea_id'], unique=False)

    op.create_table('registros_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('aprendiz_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=25), nullable=False),
    sa.Column('causal_justificacion', sa.String(length=30), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprendiz_id'], ['aprendices.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_asistencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sesion_id', 'aprendiz_id', name='uq_registro_sesion_aprendiz')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_asistencia')
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entregas_tarea_id'))

    op.drop_table('entregas')
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_ficha_id'))

    op.drop_table('tareas')
    with op.batch_alter_table('sesiones_asistencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_asistencia_ficha_id'))

    op.drop_table('sesiones_asistencia')
    op.drop_table('configuracion_alertas')
    with op.batch_alter_table('aprendices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aprendices_ficha_id'))
        batch_op.drop_index(batch_op.f('ix_aprendices_documento'))

    op.drop_table('aprendices')
    with op.batch_alter_table('fichas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fichas_codigo'))

    op.drop_table('fichas')
    with op.batch_alter_table('instructores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructores_correo'))

    op.drop_table('instructores')
    # ### end Alembic commands ###
