"""agregar_unique_index_codigo_ficha

Revision ID: 4eec9e4088ec
Revises: b2e8f1a3c5d7
Create Date: 2026-07-24 16:53:50.816697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eec9e4088ec'
down_revision = 'b2e8f1a3c5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas', schema=None) as batch_op:
        batch_op.create_index('uq_ficha_codigo_ficha', ['codigo_ficha'], unique=True, postgresql_where=sa.text('codigo_ficha IS NOT NULL'))

    with op.batch_alter_table('juicios_evaluativos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('juicios_evaluativos_huella_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_juicios_evaluativos_huella'))
        batch_op.create_index(batch_op.f('ix_juicios_evaluativos_huella'), ['huella'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juicios_evaluativos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_juicios_evaluativos_huella'))
        batch_op.create_index(batch_op.f('ix_juicios_evaluativos_huella'), ['huella'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('juicios_evaluativos_huella_key'), ['huella'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('fichas', schema=None) as batch_op:
        batch_op.drop_index('uq_ficha_codigo_ficha', postgresql_where=sa.text('codigo_ficha IS NOT NULL'))

    # ### end Alembic commands ###
