"""Agregar modelo MaterialFicha

Revision ID: 5b7cd8e199a0
Revises: 4eec9e4088ec
Create Date: 2026-07-24 20:58:11.314979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7cd8e199a0'
down_revision = '4eec9e4088ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales_ficha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiales_ficha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiales_ficha_ficha_id'), ['ficha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiales_ficha_instructor_id'), ['instructor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales_ficha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiales_ficha_instructor_id'))
        batch_op.drop_index(batch_op.f('ix_materiales_ficha_ficha_id'))

    op.drop_table('materiales_ficha')
    # ### end Alembic commands ###
