"""add_tipo_competencia

Revision ID: 5e17e5a4c24a
Revises: 5b7cd8e199a0
Create Date: 2026-07-24 21:02:38.229000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e17e5a4c24a'
down_revision = '5b7cd8e199a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juicios_evaluativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_competencia', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('juicios_evaluativos', schema=None) as batch_op:
        batch_op.drop_column('tipo_competencia')

    # ### end Alembic commands ###
