"""Add Grupo models

Revision ID: 8830d1d5813e
Revises: m36indicesfrecuentes
Create Date: 2026-09-25 15:59:14.594829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8830d1d5813e'
down_revision = 'm36indicesfrecuentes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_ficha_id'), ['ficha_id'], unique=False)

    op.create_table('grupo_aprendiz',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('aprendiz_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprendiz_id'], ['aprendices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', 'aprendiz_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insignias_otorgadas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_grupo_insignia', type_='unique')
        batch_op.drop_index(batch_op.f('ix_insignias_otorgadas_grupo_id'))
        batch_op.alter_column('aprendiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('grupo_id')

    # ### end Alembic commands ###
