"""add_missing_column

Revision ID: a4ad8b8ede5f
Revises: e2743fa83581
Create Date: 2026-07-25 17:59:42.415337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ad8b8ede5f'
down_revision = 'e2743fa83581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_mejoramiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aprendiz_id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('alerta_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('fecha_cumplimiento', sa.DateTime(), nullable=True),
    sa.Column('actividades', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones_instructor', sa.Text(), nullable=True),
    sa.Column('observaciones_aprendiz', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas.id'], ),
    sa.ForeignKeyConstraint(['aprendiz_id'], ['aprendices.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['instructores.id'], ),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planes_mejoramiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planes_mejoramiento_aprendiz_id'), ['aprendiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planes_mejoramiento_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_planes_mejoramiento_ficha_id'), ['ficha_id'], unique=False)

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_escalada', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('fecha_ultima_evaluacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('configuracion_alertas_comite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje_minimo_asistencia', sa.Integer(), server_default='75', nullable=False))
        batch_op.add_column(sa.Column('auto_escalar_dias', sa.Integer(), server_default='15', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_alertas_comite', schema=None) as batch_op:
        batch_op.drop_column('auto_escalar_dias')
        batch_op.drop_column('porcentaje_minimo_asistencia')

    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_column('fecha_ultima_evaluacion')
        batch_op.drop_column('auto_escalada')

    with op.batch_alter_table('planes_mejoramiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planes_mejoramiento_ficha_id'))
        batch_op.drop_index(batch_op.f('ix_planes_mejoramiento_estado'))
        batch_op.drop_index(batch_op.f('ix_planes_mejoramiento_aprendiz_id'))

    op.drop_table('planes_mejoramiento')
    # ### end Alembic commands ###
