"""add_sporadic_absences_config

Revision ID: e2743fa83581
Revises: 6a9b8c5d3e2f
Create Date: 2026-07-25 17:30:58.530465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2743fa83581'
down_revision = '6a9b8c5d3e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_alertas_comite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('umbral_fallas_esporadicas', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('periodo_dias_esporadicas', sa.Integer(), nullable=False, server_default='90'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_alertas_comite', schema=None) as batch_op:
        batch_op.drop_column('periodo_dias_esporadicas')
        batch_op.drop_column('umbral_fallas_esporadicas')

    # ### end Alembic commands ###
